### PR TITLE
Home page front end

### PR DESCRIPTION
**Pull request by SoftwareEngineer1014**
Fix issues on frontend side and add functions with the stake, unstake
- Fix issues when user refresh the page
- Add some limited delay 5s into congratulation UI - success message
- make progress bar dynamic
- Change Add stake component
- Add loading in the pool detail page for stake lists

### CODE REVIEW

**Comment by petry26** [comment]
I found the following issues: 

**Connect to wallet**
- "connect wallet" button on the header does not work;

- if the user refreshes the page or go to another page the wallet is disconnected, we need to stay connect with the wallet and display it accurately;

**Stake**
- add stake is not working;

**Unstake**
- unstaking is not working;

- change the style of the "Unstake" text to a pointer on the /pool page;

**Home page**
-remove padding right and left, the container is not longer necessary (remove it from all pages);
-"connect wallet" button style does not match the design;
-There is css that darkens part of the picture shown on the home page https://www.figma.com/file/tpKyM0fIBwBnQJjs9OWjmv/LaunchPools-Website?node-id=290%3A27763, add it to our app too 

**Pool list**

- Items on menu does not have the same style as the designed model;

- add space between the pools and the footer;

- add text-align: center on the h2 that contains the "sub-page" title, "Get in line early...."

- Fix the text of "Open" and "Closed" pools pages, both ot these pages have the text of the "upcoming" sub-page;

**Comment by SoftwareEngineer1014** [comment]
I fixed the issues below and committed into branch.

- connect wallet button does not work (This button is working on all pages)
- if user refresh or go to another page, the connect status is not changing (This issue is mostly fixed but if user go to another page and refresh then need to connect again - I am fixing this issue now)
- add stake is working
- unstake is working but it unstakes all the stakes based on the token in the stake list item (I am waiting for Andres's updates on unstake function to unstake only one selected stake)
- change the style of unstake (changed into hand cursor)
- remove padding right and left (remove it from all pages)
- connect wallet button style does not match the design (I changed the button style from the design)
- css darkens part of the home page background (I added gradient darken part in background image)
- items on menu does not have the same style (I fixed this issue from the design)
- add space between pools and the footer (I added the space)
- add text-align : center into sub-page title of pool list page (I added the CSS property)
- fix the text of "Open" and "Closed" pools page text (I changed the text for open, closed pools page from the design)

**Comment by SoftwareEngineer1014** [comment]
I fixed some more issues.
- Fix the redirection issue when user go back to pool list page, the selected tab is still remain
- Add validation for the metamask connection to correct blockchain network (Kovan testnet for example)
- Make able to user back from the pool detail page to pool list page

**Comment by SoftwareEngineer1014** [comment]
And fix this issue.
- Add disable click function into comming and closed pool list items

**Pull request merged**
